### ISSUE TITLE
v1.11.0 - Assets don't use the metadata name in the UTxO list

### ISSUE THREAD

**Issue by mezuny** [Tastenkunst/eternl-tracker#19]
![image](https://github.com/Tastenkunst/eternl-tracker/assets/4470326/a234ca0f-82dc-41dd-8b2f-365fc469c5a1)
![image](https://github.com/Tastenkunst/eternl-tracker/assets/4470326/116630ee-57d1-4403-aea7-2d42be4ad5cb)

**Comment by HeptaSean** [comment]
To be clear: In the UTxO list, they do not update even if they are updated in the token list:
![Image](https://github.com/Tastenkunst/eternl-tracker/assets/1820735/f0b774b9-9db3-4dcf-bec5-e135f3117aa2)

The metadata fetch in the token list being a little flaky is maybe another, independent issue? Didn't have that problem on the alpha. Perhaps because there are now more users?
